redirect_uris = "https://panelingeniar.streamlit.app/"
testing_mode = true
client_id = '217779314261-op4aepd0jdf77j69gi089s3mhv2csj5m.apps.googleusercontent.com'
client_secret = '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'
redirect_url_test = 'https://panelingeniar.streamlit.app/'
redirect_url = "https://your_app_url..."
