# .streamlit/secrets.toml
[google]
client_id = "217779314261-op4aepd0jdf77j69gi089s3mhv2csj5m.apps.googleusercontent.com"
client_secret = "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"
redirect_uris = ["https://panelingeniar.streamlit.app/"]
